### ISSUE TITLE
git config file name

### ISSUE THREAD

**Issue by RayZ0rr** [mvpopuk/dotfiles#1]
From [git config](https://git-scm.com/docs/git-config#Documentation/git-config.txt-XDGCONFIGHOMEgitconfig)  documentation, the name of config file inside `.config/git` directory should be just `config`

**Comment by mvpopuk** [comment]
`.gitconfig` was autogenerated when installing the git CLI and it was located in my root folder `~/`. What I did was just to move it in my `.dotfiles/git` folder and symlink to the original path.
