### ISSUE TITLE
Clock not displaying in Tmux

### ISSUE THREAD

**Issue by shMorganson** [mvpopuk/dotfiles#3]
I am having issues with getting the world clock to populate in the Tux config and theme. You able to help a bit? No worries if you're busy. 

![Screen Shot 2022-03-17 at 8 54 16 AM](https://user-images.githubusercontent.com/59580484/158813433-34ef2d42-a1ce-4fc4-8fb3-084167bb16f2.png)

**Comment by mvpopuk** [comment]
Have you [installed the plugin](https://github.com/mvpopuk/dotfiles/blob/main/tmux/.tmux.conf#L104) ? 

I use [tmp ](https://github.com/tmux-plugins/tpm)to manage tmux plugins. Once the plugin is installed it should work with what you have in the screenshot.
